export const translations = {
  en: {
    // Admin Layout / Common
    title: "GYM Track Admin",
    dashboard: "Dashboard",
    members: "Members",
    alerts: "Alerts",
    tracking: "Membership Tracking",
    addMember: "Add Member",
    reports: "Reports",
    settings: "Settings",
    logout: "Logout",
    language: "Amharic",
    close: "Close",
     save:"Save",
    // SettingsPage
    settings_updated: "Settings Updated",
    settings_description: "Your gym settings have been successfully saved.",
    settings_page_title: "Settings",
    settings_page_description: "Configure your gym management system preferences",

    general_settings: "General Settings",
    general_settings_description: "Basic gym information and configuration",
    gym_name: "Gym Name",
    admin_email: "Admin Email",
    member_limit: "Member Limit",

    notification_settings: "Notification Settings",
    notification_settings_description: "Configure alert and notification preferences",
    alert_days_before_expiry: "Alert Days Before Expiry",
    email_notifications: "Email Notifications",
    email_notifications_description: "Send alerts via email",
    sms_notifications: "SMS Notifications",
    sms_notifications_description: "Send alerts via SMS",

    pricing_settings: "Pricing Settings",
    pricing_settings_description: "Configure membership pricing tiers",
    monthly_membership: "Monthly Membership (ETB)",
    quarterly_membership: "Quarterly Membership (ETB/month)",
    yearly_membership: "Yearly Membership (ETB/month)",

    system_settings: "System Settings",
    system_settings_description: "Advanced system configuration options",
    auto_renewal: "Auto Renewal",
    auto_renewal_description: "Automatically renew expired memberships",
    system_status: "System Status",

    change_password: "Change Password",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    password_error_incorrect: "Current password is incorrect",
    password_error_mismatch: "New password and confirm password do not match",
    password_success: "Password changed successfully!",
    error: "Error",
    error_saving_settings: "Failed to save settings. Try again.",
    error_updating_password: "Failed to update password. Try again.",
    save_settings: "Save",
    cancel: "Cancel",

    // ReportsPage / Analytics
    gym_report: "Gym Report",
    total_members: "Total Members",
    active_members: "Active Members",
    expiring_members: "Expiring Members",
    expired_members: "Expired Members",
    new_members_this_month: "New Members This Month",
    membership_distribution: "Membership Type Distribution",
    membership_distribution_desc: "Breakdown of membership types across all members",
    monthly_members: "Monthly Members",
    quarterly_members: "Quarterly Members",
    yearly_members: "Yearly Members",
    revenue_breakdown: "Revenue Breakdown (ETB)",
    monthly_plans: "Monthly Plans",
    quarterly_plans: "Quarterly Plans",
    yearly_plans: "Yearly Plans",
    total_revenue: "Total Revenue",
    join_trends_last_6_months: "Member Join Trends (last 6 months)",
    reports_analytics: "Reports & Analytics",
    reports_analytics_desc: "Comprehensive insights into gym performance and member analytics",
    refresh: "Refresh",
    export_report: "Export Report",
    monthly_recurring_revenue: "Monthly recurring revenue",
    currently_active_memberships: "Currently active memberships",
    growth_rate: "Growth Rate",
    retention_rate: "Retention Rate",
    active_vs_total_members: "Active vs total members",
    member_join_trends: "Member Join Trends",
    new_member_registrations_last_6_months: "New member registrations over the last 6 months",
    member_status_overview: "Member Status Overview",
    current_status_all_members: "Current status of all gym members",
    expiring_soon: "Expiring Soon",
    new_this_month: "New This Month",
    monthly_revenue_by_type: "Monthly revenue by membership type",
    total_monthly_revenue: "Total Monthly Revenue",

    member_registration: "Member Registration",
    member_registration_desc: "Register a new gym member and assign membership details",
    upload_photo_optional: "Upload a photo (optional)",
    name: "Name",
    email: "Email",
    phone: "Phone",
    date_of_birth: "Date of Birth",
    address: "Address",
    emergency_contact: "Emergency Contact",
    emergency_phone: "Emergency Phone",
    membershipType: "Membership Type",
    select_membership_type: "Select membership type",
    monthly: "Monthly",
    quarterly: "Quarterly",
    yearly: "Yearly",
    register_member: "Register Member",
    registering: "Registering...",
    registration_success: "Registration Successful",
    registered_successfully: "has been registered successfully.",
    registration_failed: "Registration Failed",
    registration_failed_desc: "Something went wrong while registering the member.",
    validation_error: "Validation Error",
    fill_required_fields: "Please fill in all required fields.",
    enter_name: "Enter full name",
    enter_email: "Enter email address",
    enter_phone: "Enter phone number",
    membership_tracking: "Membership Tracking",
membership_tracking_desc: "Monitor membership status and renewal dates",
refresh_data: "Refresh Data",
data_refreshed: "Data Refreshed",
membership_tracking_updated: "Membership tracking data has been updated.",
membership_renewed: "Membership Renewed",
membership_renewed_success: "membership has been renewed successfully.",
critical: "Critical",
expired_or_7days: "Expired or expiring in 7 days",
expiring_in_30days: "Expiring in 8–15 days",
active: "Active",
more_than_30days: "More than 30 days left",
inactive: "Inactive",
suspended_memberships: "Suspended memberships",
days :"Days",
membership_alerts: "Membership Alerts",
monitor_membership_alerts: "Monitor and manage membership expiration alerts",
alert_system: "Alert System",
expiration_alerts_30days: "30-day membership expiration alerts",
alerts_refreshed: "Alerts Refreshed",
membership_alerts_updated: "Membership alerts have been updated.",
alert_dismissed: "Alert Dismissed",
alert_removed: "Alert has been removed from the list.",
expired: "Expired",
warning: "Warning",
info: "Info",
memberships_expired: "Memberships expired",
expiring_7days: "Expiring in 7 days",
expiring_8_14days: "Expiring in 8–14 days",
expiring_15_30days: "Expiring in 15–30 days",
all_clear: "All Clear!",
no_membership_alerts: "No membership alerts at this time. All memberships are in good standing.",

member_management: "Member Management",
manage_all_members: "Manage all gym members, their profiles, and membership status",
export_data: "Export Data",
exporting: "Exporting...",
add_member: "Add Member",
no_members_found: "No members found",
export_failed: "Export failed",

search_members: "Search members...",
no_members_found_search: "No members found matching your search.",
delete_member: "Delete Member",
delete_member_confirm: "Are you sure you want to delete",
member_deleted: "Member Deleted",
member_deleted_success: "has been removed from the system.",
delete: "Delete",
joined_on: "Joined on",
days_left: "days left",
days_ago: "days ago",
expires_today: "Expires today",
membership: "membership",

back_to_home: "Back to Home",
admin_dashboard: "Admin Dashboard",
manage_gym_members: "Manage your gym members and track performance",
view_alerts: "View Alerts",
key_metrics: "Key Metrics",
member_directory: "Member Directory",

back: "Back",
unknown: "Unknown",

manage_your_gym_members: "Manage your gym members and track performance",

// Member Profile
member_profile: "Member Profile",
member_profile_desc: "Detailed member information and management",
edit_profile: "Edit Profile",
renew_membership: "Renew Membership",
member_not_found: "Member Not Found",
member_not_found_desc: "The requested member could not be found",
member_id: "Member ID",
membership_details: "Membership Details",
membership_details_desc: "Current membership status and progress",
membership_progress: "Membership Progress",
started: "Started",
ends: "Ends",
membership_type: "Membership Type",
status: "Status",
days_remaining: "Days Remaining",
start_date: "Start Date",
end_date: "End Date",
last_updated: "Last Updated",
personal_info: "Personal Information",
member_since: "Member Since",
settings_desc: "Advanced system configuration options",
general_settings_desc: "Advanced system configuration options",
auto_renewal_desc: "Automatically renew expired memberships",
online: "Online",
database_connected: "Database Connected",
alerts_active: "Alerts Active",

editMemberDetails: "Edit Member Details",
dateOfBirth: "Date of Birth",
emergencyContact: "Emergency Contact",
emergencyPhone: "Emergency Phone",
selectType: "Select type",
saveChanges: "Save Changes",
profileUpdated: "'s profile has been updated successfully.",
    updateFailed: "Update Failed",
    somethingWrong: "Something went wrong while saving changes.",

    // Staff Management
    staff_management: "Staff Management",
    staff_management_desc: "Manage gym staff members and their access permissions",
    add_staff: "Add Staff",
    add_staff_member: "Add Staff Member",
    add_staff_desc: "Create a new staff account with limited access",
    edit_staff_member: "Edit Staff Member",
    edit_staff_desc: "Update staff member details",
    staff_members: "Staff Members",
    username: "Username",
    last_edited_by: "Last Edited By",
    created_by: "Created By",
    password: "Password",
    created: "Created",
    actions: "Actions",
    enter_username: "Enter username",
    enter_password: "Enter password",
    english: "English",
    amharic: "አማርኛ",
    new_password_placeholder: "Enter new password",
    save_changes: "Save Changes",
    delete_staff: "Delete Staff Member",
    delete_staff_confirm: "Are you sure you want to delete this staff member? This action cannot be undone.",
    staff_added_success: "Staff member added successfully",
    staff_updated_success: "Staff member updated successfully",
    staff_deleted_success: "Staff member deleted successfully",
    failed_to_add_staff: "Failed to add staff member",
    failed_to_update_staff: "Failed to update staff member",
    failed_to_delete_staff: "Failed to delete staff member",
    failed_to_load_staff: "Failed to load staff members",
    current_admin_not_found: "Current admin not found",
    account_deactivated: "Your account has been deactivated. Please contact your manager.",

  },

  am: {
    // Admin Layout / Common
    title: "GYM Track Admin",
    dashboard: "ዳሽቦርድ",
    members: "አባላት",
    alerts: "ማስታወቂያዎች",
    tracking: "የአባልነት ክትትል",
    addMember: "አባል መጨመር",
    reports: "ሪፖርቶች",
    settings: "ቅንብሮች",
    logout: "ውጣ",
    language: "English",
    close: "መዝጋት",

    // SettingsPage
    settings_updated: "ቅንብሮች ተስተካክሏል",
    settings_description: "የጂም ቅንብሮችዎ በተሳካ ሁኔታ ተቀይረዋል።",
    settings_page_title: "ቅንብሮች",
    settings_page_description: "የጂም አስተዳደር ስርዓት ማስተካከያ አማራጮችን ያስተካክሉ",

    general_settings: "አጠቃላይ ቅንብሮች",
    general_settings_description: "የጂም መረጃ እና አስተካከያ",
    gym_name: "የጂም ስም",
    admin_email: "አስተዳዳሪ ኢሜል",
    member_limit: "የአባል ገደብ",

    notification_settings: "የማስታወቂያ ቅንብሮች",
    notification_settings_description: "ማስታወቂያዎችን እና አማራጮችን ያስተካክሉ",
    alert_days_before_expiry: "የማስታወቂያ ቀናት ከማስፈጸሚያ",
    email_notifications: "የኢሜል ማስታወቂያዎች",
    email_notifications_description: "በኢሜል ማስታወቂያዎችን ላክ",
    sms_notifications: "የኤስኤምኤስ ማስታወቂያዎች",
    sms_notifications_description: "በስልክ ማስታወቂያዎችን ላክ",

    pricing_settings: "የዋጋ ቅንብሮች",
    pricing_settings_description: "የአባልነት ዋጋ እቃዎችን ያስተካክሉ",
    monthly_membership: "ወርሃዊ አባልነት (ETB)",
    quarterly_membership: "ሩቅ አባልነት (ETB/ወር)",
    yearly_membership: "ዓመታዊ አባልነት (ETB/ወር)",

    system_settings: "የስርዓት ቅንብሮች",
    system_settings_description: "የስርዓት ዝርዝር አማራጮች",
    auto_renewal: "ራስ-ሰርዝ እንደገና አባልነት",
    auto_renewal_description: "የተሰናከለ አባልነት በራስነት ይዘዋል",
    system_status: "የስርዓት ሁኔታ",

    change_password: "የሚለውን ቁልፍ ቀይር",
    current_password: "የአሁኑ የሚለውን ቁልፍ",
    new_password: "አዲስ የሚለውን ቁልፍ",
    confirm_password: "ያረጋግጡ አዲስ ቁልፍ",
    password_error_incorrect: "የአሁኑ ቁልፍ ትክክል አይደለም",
    password_error_mismatch: "አዲስ ቁልፍ እና የማረጋገጫ ቁልፍ የተለያዩ ናቸው",
    password_success: "ቁልፍ ተሳክቷል!",
    error: "ስህተት",
    error_saving_settings: "ቅንብሮችን ማስቀመጥ አልተሳካም። እንደገና ይሞክሩ።",
    error_updating_password: "የቁልፍ ማስተካከያ አልተሳካም። እንደገና ይሞክሩ።",
    save_settings: "አስቀመጥ",
    cancel: "ሰርዝ",
    save :"አስቀመጥ",
    // ReportsPage / Analytics
    gym_report: "የጂም ሪፖርት",
    total_members: "አጠቃላይ አባላት",
    active_members: "Active አባላት",
    expiring_members: "Expiring አባላት",
    expired_members: "Expired አባላት",
    new_members_this_month: "በዚህ ወር አዲስ አባላት",
    membership_distribution: "የአባልነት አይነት ስርዓት",
    membership_distribution_desc: "በሁሉም አባላት የአባልነት አይነት ስርዓት",
    monthly_members: "ወርሃዊ አባላት",
    quarterly_members: "ሩቅ አባላት",
    yearly_members: "ዓመታዊ አባላት",
    revenue_breakdown: "የገቢ ማብራሪያ (ETB)",
    monthly_plans: "ወርሃዊ እቃዎች",
    quarterly_plans: "ሩቅ እቃዎች",
    yearly_plans: "ዓመታዊ እቃዎች",
    total_revenue: "አጠቃላይ ገቢ",
    join_trends_last_6_months: "የአባል መቀላቀል እና ትምህርት (ከ6 ወር በኋላ)",
    reports_analytics: "ሪፖርቶች ",
    reports_analytics_desc: " መረጃ",
    refresh: "refresh",
    export_report: "ሪፖርት ላክ",
    monthly_recurring_revenue: "ወርሃዊ እድገት",
    currently_active_memberships: "Active አባልነት",
    growth_rate: "የእድገት ደረጃ",
    retention_rate: "የመቆየት ደረጃ",
    active_vs_total_members: "ንቁ እና አጠቃላይ አባላት",
    member_join_trends: "የአባል መቀላቀል ስርዓት",
    new_member_registrations_last_6_months: "ከስር ስር የአዲስ አባላት ምዝገባ እና ትምህርት",
    member_status_overview: "የአባል ሁኔታ እይታ",
    current_status_all_members: "የሁሉም አባላት አሁን ሁኔታ",
    expiring_soon: "በቅርብ የሚያልፉ",
    new_this_month: "በዚህ ወር አዲስ",
    monthly_revenue_by_type: "ወርሃዊ ገቢ በአባልነት አይነት",
    total_monthly_revenue: "አጠቃላይ ወርሃዊ ገቢ",
    last_edited_by: "ለመጨረሻ ጊዜ የተስተካከለው",
    created_by: "ለመመዝገብ ጊዜ የተስተካከለው",
    member_registration: "የአባል መመዝገቢያ",
member_registration_desc: "አዲስ የጂም አባል መመዝገብ እና የአባልነት ዝርዝሮችን መመደብ",
upload_photo_optional: "ፎቶ አስገባ (አማራጭ)",
name: "ስም",
email: "ኢሜይል",
phone: "ስልክ",
date_of_birth: "የትውልድ ቀን",
address: "አድራሻ",
emergency_contact: "የአደጋ ጊዜ የሚያነጋግሩት ሰው",
emergency_phone: "የአደጋ ጊዜ ስልክ",
membershipType: "የአባልነት አይነት",
select_membership_type: "የአባልነት አይነት ይምረጡ",
monthly: "ወርሃዊ",
quarterly: "ሩብ ዓመታዊ",
yearly: "አመታዊ",
register_member: "አባል ይመዝግቡ",
registering: "በመመዝገብ ላይ...",
registration_success: "መመዝገቡ ተሳክቷል",
registered_successfully: "በተሳካ መንገድ ተመዝግቧል።",
registration_failed: "መመዝገቡ አልተሳካም",
registration_failed_desc: "አባልን በመመዝገብ ላይ ችግኝ ተፈጥሯል።",
validation_error: "የማረጋገጫ ስህተት",
fill_required_fields: "እባክዎን አስፈላጊ መስኮችን ይሙሉ።",
enter_name: "ሙሉ ስም ያስገቡ",
enter_email: "ኢሜይል አድራሻ ያስገቡ",
enter_phone: "የስልክ ቁጥር ያስገቡ",


membership_tracking: "የአባልነት ትዕዛዝ መከታተያ",
membership_tracking_desc: "የአባልነት ሁኔታ እና የመታደሻ ቀኖችን ይከታተሉ",
refresh_data: "መረጃ ያድሱ",
data_refreshed: "መረጃ ተዘምኗል",
membership_tracking_updated: "የአባልነት መከታተያ መረጃ ተዘምኗል።",
membership_renewed: "አባልነት ታደሰ",
membership_renewed_success: "አባልነቱ በተሳካ መንገድ ታደሰ።",
critical: "አስቸኳይ",
expired_or_7days: "ያልተቀጠለ ወይም በ7 ቀን ውስጥ የሚያልቅ",
expiring_in_30days: "15 ቀን ውስጥ የሚያልቅ",
active: "ንቁ",
more_than_30days: "ከ30 ቀን በላይ ቀርቶታል",
inactive: "አልተንቀሳቀሰም",
suspended_memberships: "የተከለከሉ አባላት",
days :"ቀናት",
membership_alerts: "የአባል ማስጠንቀቂያዎች",
monitor_membership_alerts: "የአባል ማስተዳደር እና የማስታወቂያ ሁኔታ እንዲቆጥቡ ተመልከት",
alert_system: "የማስጠንቀቂያ ስርዓት",
expiration_alerts_30days: "የ30 ቀናት የአባል ማስታወቂያ ሁኔታ",
alerts_refreshed: "ማስጠንቀቂያዎች ተዘምኗል",
membership_alerts_updated: "የአባል ማስጠንቀቂያ ሁኔታዎች ተዘምኗል",
alert_dismissed: "ማስጠንቀቂያ ተሰርዟል",
alert_removed: "ማስጠንቀቂያ ከዝርዝር ተወግዷል",
expired: "ያልተጠበቀ",
warning: "አስጠንቀቂያ",
info: "መረጃ",
memberships_expired: "የአባልነት ጊዜ ከፍተኛ ያልተጠበቀ",
expiring_7days: "በ7 ቀናት ውስጥ ይዘጋል",
expiring_8_14days: "በ8–14 ቀናት ውስጥ ይዘጋል",
expiring_15_30days: "በ15–30 ቀናት ውስጥ ይዘጋል",
all_clear: "ሁሉም ጥሩ ነው!",
no_membership_alerts: "በአሁኑ ጊዜ ማንኛውም የአባል ማስጠንቀቂያ የለም። ሁሉም አባልነቶች በጥሩ ሁኔታ ላይ ናቸው።",

member_management: "የአባል አስተዳደር",
manage_all_members: "ሁሉንም የጂም አባላት፣ ፕሮፋይሎቻቸውን እና የአባልነት ሁኔታ ያስተዳድሩ",
export_data: "ውሂብ ላክ",
exporting: "ላክ የሚለው በሂደት ላይ...",
add_member: "አባል አክል",
no_members_found: "አባላት አልተገኙም",
export_failed: "ውሂብ ማስተዋወቅ አልተፈጸመም",


    search_members: "አባላትን ይፈልጉ...",
    no_members_found_search: "የተፈለጉት አባላት አልተገኙም",
    delete_member: "አባል ሰርዝ",
    delete_member_confirm: "እርግጠኛ ነህ የሚከተለውን አባል ሰርዝ",
    member_deleted: "አባል ተሰርዟል",
    member_deleted_success: "ከስርዓቱ ተወግዷል",
    delete: "ሰርዝ",
    joined_on: "ተቀላቀለ ቀን",
    days_left: "ቀናት ቀርተዋል",
    days_ago: "ቀናት በፊት ያለ",
    expires_today: "ዛሬ ይሞታል",
    membership: "አባልነት",

    back_to_home: "ወደ መነሻ ቤት ተመለስ",
    admin_dashboard: "የአስተዳደር ገጽ",
    manage_gym_members: "የጂም አባላትን ያስተዳድሩ እና አፈፃፀምን ተከታትሉ",
    view_alerts: "ማስጠንቀቂያዎችን ይመልከቱ",
    key_metrics: "ዋና ማስታወቂያዎች",
    member_directory: "የአባላት ዝርዝር",

    back: "ተመለስ",
    unknown: "ያልታወቀ",
    manage_your_gym_members: "የጂም አባላትን ያስተዳድሩ እና አፈፃፀሙን ተከታትሉ",
    settings_saved: "ቅንብሮች ተቀመጡ",
    settings_saved_desc: "ቅንብሮችዎ በተሳካ ሁኔታ ተቀመጡ።",
    settings_save_error: "ቅንብሮችን ማስቀመጥ አልተሳካም። እንደገና ይሞክሩ።",
   
    settings_updated_desc: "የጂም ቅንብሮችዎ በተሳካ ሁኔታ ተቀይረዋል።",
    settings_desc: "የጂም አስተዳደር አማራጮችን ያስተካክሉ።",
    general_settings_desc: "የጂም አስተዳደር አማራጮችን ያስተካክሉ።",
    // Member Profile
    member_profile: "የአባል መግለጫ",
    member_profile_desc: "የአባል ዝርዝር መረጃ እና አስተዳደር",
    edit_profile: "መግለጫ አርትዕ",
    renew_membership: "አባልነት ዘምን",
    member_not_found: "አባል አልተገኘም",
    member_not_found_desc: "የተጠየቀው አባል አልተገኘም",
    member_id: "የአባል መለያ",
    membership_details: "የአባልነት ዝርዝሮች",
    membership_details_desc: "የአሁኑ ሁኔታ እና እድገት",
    membership_progress: "የአባልነት እድገት",
    started: "ጀምሮ",
    ends: "ይጨርሳል",
    membership_type: "የአባልነት አይነት",
    status: "ሁኔታ",
    days_remaining: "ቀናት ቀሩ",
    start_date: "የመጀመሪያ ቀን",
    end_date: "የመጨረሻ ቀን",
    last_updated: "መጨረሻ ዝርዝር",
    personal_info: "የግል መረጃ",
    member_since: "ከዚህ ጀምሮ አባል",

    editMemberDetails: "አባል መረጃ ያስተካክሉ",
    dateOfBirth: "የትውልድ ቀን",
    emergencyContact: "የአደጋ ጊዜ እውቂያ",
    emergencyPhone: "የአደጋ ጊዜ ስልክ",
    selectType: "አይነት ይምረጡ",
    saveChanges: "ለውጦችን ያስቀምጡ",
    profileUpdated: " ፕሮፋይሉ በተሳካ ሁኔታ ተዘምኗል።",
    updateFailed: "ዝመና አልተሳካም",
    somethingWrong: "በማስቀመጥ ላይ ችግኝ ተከስቷል።",

    // Staff Management
    staff_management: "የሰራተኞች አስተዳደር",
    staff_management_desc: "የጂም ሰራተኞችን እና የመዳረሻ ፈቃዶቻቸውን ያስተዳድሩ",
    add_staff: "ሰራተኛ ጨመር",
    add_staff_member: "ሰራተኛ አባል ጨመር",
    add_staff_desc: "የተገደበ መዳረሻ ያለው አዲስ የሰራተኛ መለያ ይፍጠሩ",
    edit_staff_member: "ሰራተኛ አባል አርትዕ",
    edit_staff_desc: "የሰራተኛ አባል ዝርዝሮችን ያሻሽሉ",
    staff_members: "የሰራተኞች አባላት",
    username: "የተጠቃሚ ስም",
    password: "የይለፍ ቃል",
    created: "ተፈጥሯል",
    actions: "ድርጊቶች",
    enter_username: "የተጠቃሚ ስም ያስገቡ",
    enter_password: "የይለፍ ቃል ያስገቡ",
    english: "English",
    amharic: "አማርኛ",
    new_password_placeholder: "አዲስ የይለፍ ቃል ያስገቡ",
    save_changes: "ለውጦችን ያስቀምጡ",
    delete_staff: "ሰራተኛ አባል ሰርዝ",
    delete_staff_confirm: "ይህን የሰራተኛ አባል መሰረዝ እርግጠኛ ነዎት? ይህ ድርጊት ሊመለስ አይችልም።",
    staff_added_success: "የሰራተኛ አባል በተሳካ ሁኔታ ተጨመረ",
    staff_updated_success: "የሰራተኛ አባል በተሳካ ሁኔታ ተዘምኗል",
    staff_deleted_success: "የሰራተኛ አባል በተሳካ ሁኔታ ተሰርዟል",
    failed_to_add_staff: "የሰራተኛ አባል መጨመር አልተሳካም",
    failed_to_update_staff: "የሰራተኛ አባል ማዘመን አልተሳካም",
    failed_to_delete_staff: "የሰራተኛ አባል ማስወገድ አልተሳካም",
    failed_to_load_staff: "የሰራተኞች አባላት መጫን አልተሳካም",
    current_admin_not_found: "አሁኑ አስተዳዳሪ አልተገኘም",
    account_deactivated: "የእርስዎ መለያ ተሰናክሏል። እባክዎ ከአስተዳዳሪዎ ጋር ያገናኙ።",
  },
} as const

export type LanguageCode = keyof typeof translations
export type TranslationKeys = keyof typeof translations["en"]
